/** Checkout UI copy for FlowPay. */
export const COPY = {
  brand: "FlowPay",
  securing: "Securing your Checkout...",
  poweredBy: "Powered by",
  partnerName: "FlowPay",
  secured: "100% Secured Payment",
  whatsappBar: "Customer Care WhatsApp: +918169308591",
  orderSummary: "Order Summary",
  savedSoFar: (n: string) => `₹${n} saved so far`,
  oneItem: "1 item",
  deliverTo: "Deliver To Muralidhar Acharya",
  addressLine:
    "A-302 Shanta Jyot Shopping Center Near Po... Maharashtra, 401202",
  phone: "+91 8390001185",
  email: "muralidharacharya7@gmail.c...",
  tapToEdit: "Tap To Edit Address",
  change: "Change",
  freeShipping: "Free Shipping",
  warranty: "1 Year Replacement Warranty",
  free: "Free",
  offersLabel: "OFFERS & REWARDS",
  couponPlaceholder: "Enter coupon code",
  paymentLabel: "PAYMENT OPTIONS",
  upiTitle: "UPI",
  scanInstr: "Open any UPI Apps & scan QR Code to pay",
  scanQrShort: "Scan QR code to pay",
  showQr: "Show QR",
  pci: "PCI DSS Certified",
  securedPayments: "100% SECURED Secured Payments",
  verifiedMerchant: "Verified Merchant",
  legalPrefix: "By proceeding, I agree to FlowPay's",
  privacy: "Privacy Policy",
  and: "and",
  tc: "T&C",
  loggedIn: "Logged in using",
  logout: "Logout",
  modalOrderSummary: "Order Summary",
  productName: "Version M1 - White",
  qty: "Qty: 1",
  mrpTotal: "MRP Total",
  discountOnMrp: "Discount on MRP",
  subtotal: "Subtotal",
  standardShipping: "Standard Shipping",
  toPay: "To Pay",
} as const;
